# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot, pyqtSignal
from PyQt5.QtWidgets import QMainWindow
import math

class Ui_ResultWindow(QMainWindow):
    def __init__(self):
        super(Ui_ResultWindow, self).__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("self")
        self.resize(765, 648)
        self.setStyleSheet("#centralwidget {\n"
"    background-color: rgb(60, 42, 77);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setStyleSheet("color:rgb(60, 42, 77);")
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(290, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color:rgb(224, 240, 234)")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.resultLineEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.resultLineEdit.setGeometry(QtCore.QRect(10, 150, 741, 411))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.resultLineEdit.setFont(font)
        self.resultLineEdit.setStyleSheet("border-radius: 25px;\n"
"background-color:rgb(224, 240, 234);\n"
"border: 2px solid rgb(149, 173, 190);\n"
"")
        self.resultLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLineEdit.setObjectName("resultLineEdit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(7, 50, 751, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 72, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(149, 173, 190)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.okPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.okPushButton.setGeometry(QtCore.QRect(330, 580, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.okPushButton.setFont(font)
        self.okPushButton.setStyleSheet("border-radius: 20px;\n"
"border-color:rgb(87, 79, 125);\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(149, 173, 190);\n"
"border: 2px solid white;")
        self.okPushButton.setObjectName("okPushButton")
        self.nameResultLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameResultLineEdit.setGeometry(QtCore.QRect(330, 70, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameResultLineEdit.setFont(font)
        self.nameResultLineEdit.setStyleSheet("border-radius: 25px;\n"
"background-color:rgb(224, 240, 234);\n"
"border: 2px solid rgb(149, 173, 190);\n"
"")
        self.nameResultLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.nameResultLineEdit.setObjectName("nameResultLineEdit")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "The Result"))
        self.label_7.setText(_translate("MainWindow", "The Used Method:"))
        self.okPushButton.setText(_translate("MainWindow", "OK"))

    @pyqtSlot(list)
    def show_results(self, output_list_r):
        self.resultLineEdit.clear()
        string1 = ""
        for i in output_list_r:
            string1 = string1 + i + '\n'
        print("test string", string1)
        self.resultLineEdit.setText(string1+'\n')

    @pyqtSlot(str)
    def show_method_name(self, method_name):
        self.nameResultLineEdit.clear()
        self.nameResultLineEdit.setText(method_name)